version: "3"
services:
  app:
    build:
      context: . # Use the current directory as the build context
      dockerfile: Dockerfile # Specify the Dockerfile to use
    image: SMPM1 # Replace with your desired image name
    container_name: SMPM1 # Replace with your desired container name
    restart: always
    ports:
      - "80:80"
